export const LOAD_TYPE_FILTER = "LOAD_TYPE_FILTER";
export const DELETE_ALL_FILTER = "DELETE_ALL_FILTER";
export const LOAD_KEYWORD_FILTER = "LOAD_KEYWORD_FILTER";
export const LOAD_FORMATS_FILTER = "LOAD_FORMATS_FILTER";
export const LOAD_CATS_FILTER = "LOAD_CATS_FILTER";
export const LOAD_DATE_FILTER = "LOAD_DATE_FILTER";
export const LOAD_IMPACTS_FILTER = "LOAD_IMPACTS_FILTER";
export const LOAD_ACTIONS_FILTER = "LOAD_ACTIONS_FILTER";
